### ISSUE TITLE
Snowflake excel add-in not working

### ISSUE THREAD

**Issue by MeghanaKashyap** [Snowflake-Labs/Excelerator#33] opened 2022-08-08 06:04 UTC
Connection initialization is failing with the following error message.
<img width="342" alt="connection issue" src="https://user-images.githubusercontent.com/44397381/183349975-7db4be44-a53c-4d16-bc86-7b0bfc1bd76e.PNG">

**Comment by ssegal100** [comment] 2022-08-08 13:26
Would you please describe all the steps prior to this error?
Also, would you look in the History tab of the Snowflake UI and let me know the last few queries executed and the one that is causing this error.

**Comment by RaghuveerPendyala** [comment] 2022-08-18 04:20
I ran into a similar issue and below are the queries that got executed 
![image](https://user-images.githubusercontent.com/78722648/185292383-0337a9d0-7e40-4126-8026-c0cef6ca5927.png)

Looks like  we are getting two additional columns when executing show databases which is causing this failure

**Comment by ssegal100** [comment] 2022-08-18 12:38
@RaghuveerPendyala @MeghanaKashyap 
Would you please show me the output of:
show databases;
show terse databases;

If you are getting different columns then maybe I'll have to switch to use 'show terse databases;'.
I don't know why it would be different though.
Thanks.

**Comment by RaghuveerPendyala** [comment] 2022-08-18 16:19
Show database : 
![image](https://user-images.githubusercontent.com/78722648/185442586-90dc94a7-bb37-44cd-8088-5344e61cee50.png)
show terse database : 
![image](https://user-images.githubusercontent.com/78722648/185442723-35a735e8-bf94-4cb9-996b-d72b1d5deacd.png)

I tried doing a quick check using show terse database and even it has mismatch of count of columns 
![image](https://user-images.githubusercontent.com/78722648/185442996-427f656f-c058-40d9-a55d-d96ae61fa8df.png)

Instead of doing select * from result_scan , can we select only "name" which contains the database name and this way there is no impact to Snowflake Excel Add-in as a result of future changes from Snowflake.

show databases;
WITH databases (name) as (select "name" from table(result_scan(last_query_id()))) select name from databases;

**Comment by ssegal100** [comment] 2022-08-18 16:33
@RaghuveerPendyala Yes that is the best solution.
Thank you!
I'm going to hunt down the reason for the last 2 columns from showing up. I've never seen them before. But you are right, I will just pull the 'name' column only.

**Comment by ssegal100** [comment] 2022-09-27 00:33
@RaghuveerPendyala I've uploaded a version with the changes to the query. Please test and close this issue if it's working properly.
The reason that this is an issue is that the Show Databases command returns different columns based on if certain features are enabled in the Snowflake account.

**Comment by RaghuveerPendyala** [comment] 2022-09-27 02:40
Thanks @ssegal100 , I can confirm fix is working for me

**Comment by MeghanaKashyap** [comment] 2022-09-28 08:18
Thank you so much for fixing this indeed a great help! 👍  @ssegal100

**Closed** 2022-09-28 08:17 UTC
