### ISSUE TITLE
Last option is missing -- "Auto-generate data types when not specified for new columns or a new table " Stored Procedures needed".

### ISSUE THREAD

**Issue by schenjgc** [Snowflake-Labs/Excelerator#12] opened 2021-01-26 18:44 UTC
I am missing the 3rd check box under advanced options:

"Auto-generate data types when not specified for new columns or a new table " Stored Procedures needed".

I am using the most recent SnowflakeExcelAddin.xlam (1/22/21) x64 add in

Thanks

**Comment by ssegal100** [comment] 2021-01-26 19:00
@schenjgc Due to some complications we removed this feature. 
Is it something that would be important to you? The other way of loading new columns would be to explicitly set the datatype.
I'd like to get a understanding of the value it would add to help determine if we should work at enabling it.
Thanks!
Steve

**Comment by schenjgc** [comment] 2021-01-28 17:00
when I try creating a new table I get the error:
Error executing SQL: SQL compilation error:
Object 'DEMO_DB.PUBLIC.EXAMPLE' does not exist or not authorized

**Comment by ssegal100** [comment] 2021-01-28 17:14
Did you check the 'Create new table and upload' checkbox at the bottom of the page?

**Comment by schenjgc** [comment] 2021-01-28 17:19
Yes its checked.

**Comment by schenjgc** [comment] 2021-01-28 17:27
The only way I'm able to get data into Snowflake from excel is if I first create the table in Snowflake in the same format as excel:

create or replace table "DEMO_DB"."PUBLIC".bbg_example3(DATE date, LB double, GPS double, URBN double);

insert into "DEMO_DB"."PUBLIC".bbg_example3 values
    ('2021-01-11', 46.91, 22.39, 28.65);

Then I query the table from excel using excelerator and then I add the data I want to upload into the table that was returned from my query in Excel.

**Comment by ssegal100** [comment] 2021-01-28 17:39
I think I might have found the issue. Let me test it and I'll let you know soon.

**Comment by ssegal100** [comment] 2021-01-28 18:54
@schenjgc I resolve the issue. Would you please download the latest and test again. Please let me know the results.
Thanks.
Steve

**Comment by schenjgc** [comment] 2021-01-28 19:13
Fixed! Thank you!

**Comment by ssegal100** [comment] 2021-01-28 19:16
Great, I'll close the issue.

**Closed by ssegal100** 2021-01-28 19:16 UTC

**Comment by schenjgc** [comment] 2021-01-28 21:20
A couple more questions if you can:
Does the data in excel need to be in a Table format to uplaod? And do inserts without updating the rest of the table take exceptionally long?

From: Stephen Chen
Sent: Thursday, January 28, 2021 2:14 PM
To: Snowflake-Labs/Excelerator <reply@reply.github.com>; Snowflake-Labs/Excelerator <Excelerator@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Snowflake-Labs/Excelerator] Last option is missing -- "Auto-generate data types when not specified for new columns or a new table " Stored Procedures needed". (#12)

Fixed! Thank you!

**Comment by ssegal100** [comment] 2021-01-28 21:35
Q: Does the data in excel need to be in a Table format to uplaod? 
A: It doesn't need to be an Excel table, but it does need to have the column names in the first row or the second row if you define the columns datatypes for new columns. It can't have any blank columns to the left of the data.

Q:And do inserts without updating the rest of the table take exceptionally long?
A:Updates should be pretty fast. How long are you seeing?
But to answer the question, if you check 'Insert all data...' or 'Replace all data...' it will be faster since it doesn't have to do a merge, which compares every row.

Also, just so you know, you don't have to upload all the columns or all the rows. If columns or rows are missing from the spreadsheet, it will just ignore them, unless you choose the replace option. 
Hope this helps.

**Comment by schenjgc** [comment] 2021-02-02 00:50
Hey Steven,
Replacing all data and creating new tables works now but I'm having issues on updates and inserts.

Anytime I try to insert it gives me a SQL compilation error: unsupported data type 'LB' since it appears to think I'm defining data types in the first column when they are just column names.
If I then try to define the data types it errors and says the column headers I have already exist and that you should not define the data type for a column that already exists.
Updates also run into similar errors.

It seems like the only updates that work are adding columns

**Comment by ssegal100** [comment] 2021-02-02 01:21
@schenjgc I'm unable to reproduce that.  Would create a sample excel file without any sensitive data and upload it here?
