### ISSUE TITLE
Error on SHOW GRANTS When Uploading Data to Snowflake

### ISSUE THREAD

**Issue by SuccinctGasca** [Snowflake-Labs/Excelerator#43] opened 2023-07-11 09:27 UTC
**Symptom**:
I am able to connect and get a list of databases, but when I attempt to upload a small table to Snowflake, I get the following error:

"SQL Compilation Error:
Mismatch between the number of columns produced by "SHOWGRANTS" and the number of aliases specified."
![Excelerator Error](https://github.com/Snowflake-Labs/Excelerator/assets/122592613/073a59bc-336a-439f-90b3-c538b2610afa)

Last statement executed on Snowflake:
with ShowGrants (created_on,privilege,granted_on,name,granted_to,grantee_name,grant_option,granted_by) as (select * from  table(result_scan(last_query_id()))) select 'grant '|| privilege|| ' on table ' || '"DB_NAME"."DBO"."TEST2234100_BackupForExcel"' || ' to '|| granted_to ||' ' || grantee_name || IFF( grant_option='true' , ' with grant option' ,'' ) from ShowGrants where privilege <>'OWNERSHIP' order by created_on desc

**System Info:**
Excelerator: The latest version on the Main branch as of Today
Windows 10 Pro Version 10.0.19045
Microsoft® Excel® for Microsoft 365 MSO (Version 2306 Build 16.0.16529.20100) 64-bit

**Comment by tecampbell** [comment] 2023-07-13 17:11
Same issue here.  Is this issue being worked?

Thanks,
Terry

**Comment by tecampbell** [comment] 2023-07-13 18:15
Proposed fix - 

Function grantAllPrivsToClonedTableSQL(origTable As String, clonedTable As String)
    Dim sql As String

    Call Utils.execSQLFireAndForget("show grants on " & origTable)
    sql = "with ShowGrants (created_on,privilege,granted_on,name,granted_to,grantee_name,grant_option,granted_by, granted_by_role_type) as " & _
    "(select ""created_on"",""privilege"",""granted_on"",""name"",""granted_to"",""grantee_name"",""grant_option"",""granted_by"",""granted_by_role_type"" from  table(result_scan(last_query_id()))) " & _
    "select 'grant '|| privilege|| ' on table ' || '" & clonedTable & "' || ' to '|| granted_to ||' ' || grantee_name || " & _
    "IFF( grant_option='true' , ' with grant option' ,'' ) " & _
    "from ShowGrants where privilege <>'OWNERSHIP' order by created_on desc"

    grantAllPrivsToClonedTableSQL = Utils.execSQLReturnConcatResults(sql, "~")
End Function

**Comment by miro-licek** [comment] 2023-07-19 12:57
@ssegal100 : after adding _granted_by_role_type_ into function grantAllPrivsToClonedTableSQL of _Load_ script the issue is solved. If you grant me necessary permissions I can push new fix branch and create PR for your review.

**Comment by ssegal100** [comment] 2023-07-20 18:44
@miro-licek Thank you so much. How can I give you access?

**Comment by pankaj-k** [comment] 2023-07-25 04:34
What changed at Snowflake level? I am also seeing this error.

**Comment by tecampbell** [comment] 2023-07-25 11:41
The number of columns returned by the SHOW GRANTS call changed.  

Proposed fix (I have updated my local copy and it works perfect) -

Function grantAllPrivsToClonedTableSQL(origTable As String, clonedTable As String)
Dim sql As String

Call Utils.execSQLFireAndForget("show grants on " & origTable)
sql = "with ShowGrants (created_on,privilege,granted_on,name,granted_to,grantee_name,grant_option,granted_by, granted_by_role_type) as " & _
"(select ""created_on"",""privilege"",""granted_on"",""name"",""granted_to"",""grantee_name"",""grant_option"",""granted_by"",""granted_by_role_type"" from  table(result_scan(last_query_id()))) " & _
"select 'grant '|| privilege|| ' on table ' || '" & clonedTable & "' || ' to '|| granted_to ||' ' || grantee_name || " & _
"IFF( grant_option='true' , ' with grant option' ,'' ) " & _
"from ShowGrants where privilege <>'OWNERSHIP' order by created_on desc"

grantAllPrivsToClonedTableSQL = Utils.execSQLReturnConcatResults(sql, "~")
End Function

**Comment by cschlagel** [comment] 2023-07-25 13:14
How do we implement this fix on our own copy @tecampbell?  Can you give me steps to add this code above?

**Comment by pankaj-k** [comment] 2023-07-25 13:34
Can we expect a patch soon?

**Comment by SuccinctGasca** [comment] 2023-07-25 13:39
It's a great tool. Would be awesome if the creators are still maintaining it! Fingers crossed

**Comment by tecampbell** [comment] 2023-07-25 13:59
> a

Open a spreadsheet.   Click Developer and open the VB Modules.  Search for the function   grantAllPrivsToClonedTableSQL nd replace it with this code - 

Function grantAllPrivsToClonedTableSQL(origTable As String, clonedTable As String)
Dim sql As String

Call Utils.execSQLFireAndForget("show grants on " & origTable)
sql = "with ShowGrants (created_on,privilege,granted_on,name,granted_to,grantee_name,grant_option,granted_by, granted_by_role_type) as " & _
"(select ""created_on"",""privilege"",""granted_on"",""name"",""granted_to"",""grantee_name"",""grant_option"",""granted_by"",""granted_by_role_type"" from table(result_scan(last_query_id()))) " & _
"select 'grant '|| privilege|| ' on table ' || '" & clonedTable & "' || ' to '|| granted_to ||' ' || grantee_name || " & _
"IFF( grant_option='true' , ' with grant option' ,'' ) " & _
"from ShowGrants where privilege <>'OWNERSHIP' order by created_on desc"

grantAllPrivsToClonedTableSQL = Utils.execSQLReturnConcatResults(sql, "~")
End Function


Click Save.

**Comment by ssegal100** [comment] 2023-07-25 15:13
This happened because there was a new column added to ShowGrants. My design of using 'Select *' was a very bad choice and caused this issue. As you see, the above solution calls out the needed columns explicitly, a much better durable design.
I'll get a patch out very soon but in the mean time you can update your copy by following the steps above.
Steve

**Comment by pankaj-k** [comment] 2023-07-25 21:48
Thanks @ssegal100. Awaiting the updates.

**Comment by ssegal100** [comment] 2023-07-27 12:18
@pankaj-k Would you test the file SnowflakeExcelAddinWithGrantFix.xlam? I've made the change.
If it works for you I'll replace the original.
I'm unable to test due to an issue with my laptop.
Thanks.

**Comment by sfc-gh-ssegal** [comment] 2023-07-27 15:04
@pankaj-k I made that typo change and pushed the new Addins.
Would someone test the new Addin and then we can close this issue.

Thanks for you help everyone.
Steve

**Comment by Francis-Beaulieu** [comment] 2023-07-27 18:05
I am pleased to formally confirm that the issue has been resolved

**Comment by tecampbell** [comment] 2023-07-27 18:19
[like]  Terrance Campbell reacted to your message:
________________________________
From: Francis-Beaulieu ***@***.***>
Sent: Thursday, July 27, 2023 6:05:54 PM
To: Snowflake-Labs/Excelerator ***@***.***>
Cc: Terrance Campbell ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Snowflake-Labs/Excelerator] Error on SHOW GRANTS When Uploading Data to Snowflake (Issue #43)


This email originated outside of PODS. Please verify sender before clicking links or opening attachments!
________________________________
I am pleased to formally confirm that the issue has been resolved

**Comment by sfc-gh-ssegal** [comment] 2023-07-27 18:32
Thanks everyone,
Steve

**Closed by sfc-gh-ssegal** 2023-07-27 18:32 UTC

**Comment by tecampbell** [comment] 2023-07-27 18:51
[like]  Terrance Campbell reacted to your message:
________________________________
From: Steven Segal ***@***.***>
Sent: Thursday, July 27, 2023 6:32:22 PM
To: Snowflake-Labs/Excelerator ***@***.***>
Cc: Terrance Campbell ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Snowflake-Labs/Excelerator] Error on SHOW GRANTS When Uploading Data to Snowflake (Issue #43)


This email originated outside of PODS. Please verify sender before clicking links or opening attachments!
________________________________
Closed #43<https://protect-us.mimecast.com/s/4Ja_C68zPKT1z7K2u6-lUg?domain=github.com> as completed.
